name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Releasify
        uses: teneplaysofficial/releasify-action@v1
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: "🚀 New Release!"
          footer: "Published by Slamwise"
          username: "Update Peddler"
          avatar_url: ""
